language: java
script:
  - ./gradlew build clean build -x test
  - ./gradlew javadoc
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build/docs/javadoc/
  on:
    branch: master
